function update_game()
  update_starfield()
  update_ship()
  update_bullets()
  update_enemies()
  update_pickups()
  update_collisions()
  check_next_wave()
  check_game_over()
end

function draw_game()
  draw_flash()
  draw_starfield()
  draw_ship()
  draw_muzzle()
  draw_pickups()
  draw_enemies()
  draw_shwaves()
  draw_particles()
  draw_bullets()
  draw_floats()
  draw_hud()
end