function draw_game()
  draw_flash()
  draw_starfield()
  draw_ship()
  draw_muzzle()
  draw_pickups()
  draw_enemies()
  draw_shwaves()
  draw_particles()
  draw_bullets()
  draw_floats()
  draw_hud()
end